spring.application.name=e-wallet

jwt.secret=${JWT_SECRET:this-is-a-strong-long-enough-jwt-secret}
jwt.expiration-minutes=60

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ewallet}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# spring.h2.console.enabled=true
# spring.datasource.url=jdbc:h2:mem:ewallet
